---
language: python
python:
  - 2.7
install:
  - pip install --editable .[test]
  - pip install coveralls
script:
  PYTHONPATH=. coverage run --source=src/den tests/test_den.py
after_success:
  coveralls
